export const ORDER_SET_TYPE = "ORDER_SET_TYPE";
export const CATEGORY_LIST_GET = "CATEGORY_LIST_GET";


export const PRODUCT_LIST_GET = 'PRODUCT_LIST_GET';


export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';


export const ORDER_ADD_ITEM = 'ORDER_ADD_ITEM';
export const ORDER_REMOVE_ITEM = 'ORDER_REMOVE_ITEM';
export const ORDER_CLEAR = 'ORDER_CLEAR';
export const ORDER_GET = 'ORDER_GET';


export const SCREEN_SET_WIDTH = 'SCREEN_SET_WIDTH';

export const CURRENCY_SYMBOL ="€";